# Generated by Django 2.2.7 on 2019-11-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='country',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='town_or_city',
        ),
    ]
