# Generated by Django 2.2.7 on 2019-11-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_lineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
            preserve_default=False,
        ),
    ]
