# Generated by Django 2.2.7 on 2019-11-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20191120_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='country',
        ),
    ]
