# Generated by Django 2.2.7 on 2019-11-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20191120_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='country',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='charge',
            name='street_address1',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='street_address2',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='town_or_city',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
