# Generated by Django 2.2.7 on 2019-11-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20191120_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='country',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='town_or_city',
        ),
        migrations.AlterField(
            model_name='charge',
            name='street_address2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
