# Generated by Django 2.2.7 on 2019-11-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20191121_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='line_item',
            field=models.ManyToManyField(to='checkout.LineItem'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
