# Generated by Django 2.2.7 on 2019-11-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20191121_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='line_item',
            new_name='line_items',
        ),
    ]
