# Generated by Django 2.2.7 on 2019-11-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20191121_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('uncollected', 'Uncollected'), ('collected', 'Collected')], max_length=50),
        ),
    ]
