# Generated by Django 2.2.7 on 2019-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20191123_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='postcode',
            field=models.CharField(max_length=6),
        ),
    ]
